
PRO mk_umrotse_help,whichlib,list=list
;+
; NAME:
;   MK_UMIDL_HELP
; PURPOSE:
;   This program generates help files for umidl procedure directories.
;   
; CALLING SEQEUNCE:
;   mk_local_help 
; NOTES:
;   Modified from Eric Deutch's program. Erin Scott Sheldon ??/12/99
;   Uses my program pro2html.pro to make a nice html version of each
;   procedure.
;-

  htmlfile='umich_rotse_idl.html'
;  IDL_MAIN='/sdss3/products/idltools/um_idl/umrotse_idl/'
  IDL_MAIN='/rotse2/data0/products/idltools/umrotse_idl/'
  IDL_HTML_DIR='/sdss3/usrdevel/esheldon/WWW/idlhelp/rotseidl/'
  HEADER_FILE='/sdss3/usrdevel/esheldon/WWW/idlhelp/rotseidl/headers/mk_local_help.header.html'
  FOOTER_FILE='/sdss3/usrdevel/esheldon/WWW/idlhelp/rotseidl/headers/mk_local_help.footer.html'
  TITLE='UMich IDL Homepage'

  libdirs $
    =[ $
       'darktools', "darktools", "Dark Exposure Tools", $
       'findburst', "findburst", "Tools for Finding Bursts", $
       'match', "Matching Tools", 'ROTSE matching tools',$
       'match_db', "Database Matching Tools", "New Database Matching Routines",$
       'newpipe', "Newpipe Tools", '??', $
       'pipeline', "Pipeline Tools", 'Image Pipeline Tools', $
       'temptools', "Temporary Tools", '??', $
       'tools',"Tools", 'General Tools', $
       'variables', "Variables Tools",'Variable Star Tools' $
     ]


  IF (n_elements(list) NE 0) THEN BEGIN 
      FOR i=0,n_elements(libdirs)-2,2 DO BEGIN 
          print,i,'  ',libdirs(i),' ## ',libdirs(i+1)
      ENDFOR 
      return 
  ENDIF 

  stlib=0 & enlib=n_elements(libdirs)-2
  IF (n_elements(whichlib) NE 0) THEN BEGIN 
      stlib=whichlib & enlib=whichlib
  ENDIF 


  openw,outfile,IDL_HTML_DIR+htmlfile,/get_lun
  openw,outidx,'dirindex.dat',/get_lun
  printf,outfile,'<!-- This file was generated by mk_umidl_help.pro -->'
  
  openr,hdrfile,HEADER_FILE,/get_lun
  lin=''
  WHILE NOT EOF(hdrfile) DO BEGIN 
      readf,hdrfile,lin
      printf,outfile,lin 
  ENDWHILE 
  free_lun,hdrfile

  printf,outfile,'These are IDL tools created by the ROTSE team at Michigan.'

  printf,outfile,''
  printf,outfile,'<TABLE border cellpadding=10>'
  printf,outfile,'<TR> <TH> Library Name </TH><TH> Last Update </TH><TH> Comments </TH></TR>'
  
  ntot = 0L
  FOR i=stlib, enlib,3 DO BEGIN 
      
      ctr=i/2+1
      libname='library'+strn(ctr,len=2,padchar='0')+'.html'

      printf,outidx,strn(ctr,len=2,padchar='0')+' '+IDL_MAIN+libdirs(i)
      print,'Building html file for library in ',+libdirs(i)

      ;; make a directory to put html files in
      HTML_LIB_DIR = IDL_HTML_DIR+libdirs[i]+'/'
      IF NOT exist(HTML_LIB_DIR) THEN spawn,'mkdir '+HTML_LIB_DIR,answer

      lastmod='-'
      IF (exist(IDL_MAIN+libdirs(i)+'/LAST_UPDATE')) THEN BEGIN 
          openr,5,IDL_MAIN+libdirs(i)+'/LAST_UPDATE'
          readf,5,lastmod
          close,5
      ENDIF ELSE lastmod = 'No info'

      findstr = IDL_MAIN+libdirs[i]+'/*.pro'
      files = findfile(findstr)
      nfile = n_elements(files) & ntot=ntot+nfile
      delvarx, pronames, htmlnames
      FOR fi=0L, nfile-1 DO BEGIN 
          dirsep, files[fi], tmpdir, proname
          proname = ( str_sep(proname, '.pro') )[0]
          htmlname = proname + '.html'
          pro2html, files[fi], HTML_LIB_DIR+htmlname, /silent        
          add_arrval, strupcase(proname), pronames
          add_arrval, htmlname, htmlnames
      ENDFOR 

      npro = n_elements(pronames)

      libfile = IDL_HTML_DIR+libname
      openw, liblun, libfile, /get_lun
      printf, liblun, '<HTML>'
      printf, liblun, '<HEAD><TITLE>'+libdirs[i+1]+'</TITLE></HEAD>'
      printf, liblun, '<BODY bgcolor="white" link="#0066ff" vlink="#ff0000" text="#00000">'
      printf, liblun, '<H1>'+libdirs[i+1]+'</H1><P>'
      printf, liblun, '<HR>'
      printf, liblun, '<H1>List of Routines</H1><P>'
      printf, liblun, '<UL>'
      FOR np=0, npro-1 DO BEGIN 
          printf, liblun, '<LI><A href="./'+libdirs[i]+'/'+htmlnames[np]+'">'+pronames[np]+'</A>'
      ENDFOR 
      printf, liblun, '</UL><P>'
      printf, liblun, '<HR>'
      printf, liblun, 'This file was generated by mk_umidl_help.pro.<br>'
      printf, liblun, 'Contact <A HREF="mailto:esheldon@umich.edu">esheldon@umich.edu</A> for more information.<br>'
      printf, liblun, '<b>Last modified</b> '+lastmod+'<br>'
      printf, liblun, '</BODY>'
      printf, liblun, '</HTML>'
      free_lun, liblun
            
      ;; link to the html help file.
      tmpstr='<TR> <TD nowrap> <A HREF="'+libname+'">'+libdirs(i+1)+'</A></TD> <TD nowrap> '+strn(lastmod)+'</TD><TD>'+libdirs(i+2)+' </TR>'
      
      printf,outfile,tmpstr

  ENDFOR 
  
  print
  print,'Processed ',ntostr(ntot),' .pro files'
  print

  printf,outfile,'</TABLE>'
;  printf,outfile,'<HR size=3 noshade><BR>'
  dt=strmid(!stime,0,11)
  printf,outfile,'<H0><I>This page last updated on <strong>'$
    +dt+'</strong></I></H0><BR>'

  openr,ftrfile,FOOTER_FILE,/get_lun
  lin=''
  WHILE NOT EOF(ftrfile) DO BEGIN 
      readf,ftrfile,lin
      printf,outfile,lin
  ENDWHILE
  free_lun,ftrfile
  free_lun,outfile
  free_lun,outidx
end

